[package]
name = "jevy-binaries"
version = "0.1.0"
edition = "2021"

[dependencies]
fs_extra = "1.3"
anyhow = "1.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.1"
tar = "0.4"
